# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: 11
        postgresql db: oauth
        postgresql user: postgres
        postgresql password: postgres
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B clean package -DskipTests
    - name: Maven Verify
      run: mvn -B clean verify
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.3
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
